---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "install NodeJS and NPM"
  apt:
    name:
      - nodejs
      - npm
    state: present

- name: "install pm2"
  npm:
    name: pm2
    global: yes

- name: "create web directory"
  file:
    path: ~/web
    state: directory

- name: "Copy the app to the server"
  copy:
    src: index.js
    dest: ~/web/index.js

- name: "Start the app"
  shell: pm2 start ~/web/index.js -f
