version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "install node modules"
          command: "npm i"
      - save_cache:
          paths:
            - "./node_modules"
          key: Nudes
      - run:
          name: lint
          command: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: Nudes
      - run:
          name: "install node modules"
          command: "npm i"
      - run:
          name: test
          command: npm run test
  analysis:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "analysis"
          command: npm audit

workflows:
  build-workflow:
    jobs:
      - build
      - test:
          requires:
            - "build"
      - analysis:
          requires:
            - "test"
